const TECH_STACK = [
    // Languages
    { id: 'javascript', name: 'JavaScript', category: 'Languages', icon: 'javascript' },
    { id: 'typescript', name: 'TypeScript', category: 'Languages', icon: 'typescript' },
    { id: 'python', name: 'Python', category: 'Languages', icon: 'python' },
    { id: 'java', name: 'Java', category: 'Languages', icon: 'java' },
    { id: 'cpp', name: 'C++', category: 'Languages', icon: 'cplusplus', customIconUrl: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/cplusplus/cplusplus-original.svg', link: 'https://www.w3schools.com/cpp/' },
    { id: 'csharp', name: 'C#', category: 'Languages', icon: 'csharp' },
    { id: 'go', name: 'Go', category: 'Languages', icon: 'go' },
    { id: 'rust', name: 'Rust', category: 'Languages', icon: 'rust' },
    { id: 'php', name: 'PHP', category: 'Languages', icon: 'php' },
    { id: 'ruby', name: 'Ruby', category: 'Languages', icon: 'ruby' },
    { id: 'swift', name: 'Swift', category: 'Languages', icon: 'swift' },
    { id: 'scala', name: 'Scala', category: 'Languages', icon: 'scala' },

    // Mobile Development
    { id: 'dart', name: 'Dart', category: 'Mobile Development', icon: 'dart' },
    { id: 'android', name: 'Android', category: 'Mobile Development', icon: 'android' },
    { id: 'kotlin', name: 'Kotlin', category: 'Mobile Development', icon: 'kotlin' },
    { id: 'flutter', name: 'Flutter', category: 'Mobile Development', icon: 'flutter' },
    { id: 'reactnative', name: 'React Native', category: 'Mobile Development', icon: 'react' },
    { id: 'ionic', name: 'Ionic', category: 'Mobile Development', icon: 'ionic' },
    { id: 'nativescript', name: 'NativeScript', category: 'Mobile Development', icon: 'nativescript', customIconUrl: 'https://raw.githubusercontent.com/detain/svg-logos/780f25886640cef088af994181646db2f6b1a3f8/svg/nativescript.svg', link: 'https://nativescript.org/' },

    // AI / ML
    { id: 'tensorflow', name: 'TensorFlow', category: 'AI / ML', icon: 'tensorflow' },
    { id: 'pytorch', name: 'PyTorch', category: 'AI / ML', icon: 'pytorch' },
    { id: 'pandas', name: 'Pandas', category: 'AI / ML', icon: 'pandas' },
    //{ id: 'seaborn', name: 'Seaborn', category: 'AI / ML', icon: 'seaborn', customIconUrl: 'https://cdn.simpleicons.org/seaborn/3776AB', link: 'https://seaborn.pydata.org/' },
    { id: 'seaborn', name: 'Seaborn', category: 'AI / ML', customIconUrl: 'https://seaborn.pydata.org/_images/logo-mark-lightbg.svg', link: 'https://seaborn.pydata.org/' },
    { id: 'numpy', name: 'NumPy', category: 'AI / ML', icon: 'numpy' },
    { id: 'opencv', name: 'OpenCV', category: 'AI / ML', icon: 'opencv' },
    { id: 'scikitlearn', name: 'Scikit-Learn', category: 'AI / ML', icon: 'scikitlearn', customIconUrl: 'https://cdn.simpleicons.org/scikitlearn/F7931E', link: 'https://scikit-learn.org/' },
    { id: 'kaggle', name: 'Kaggle', category: 'AI / ML', icon: 'kaggle' },

    // Frontend
    { id: 'react', name: 'React', category: 'Frontend', icon: 'react' },
    { id: 'nextjs', name: 'Next.js', category: 'Frontend', icon: 'nextjs' },
    { id: 'vue', name: 'Vue.js', category: 'Frontend', icon: 'vuejs' },
    { id: 'angular', name: 'Angular', category: 'Frontend', icon: 'angularjs' },
    { id: 'svelte', name: 'Svelte', category: 'Frontend', icon: 'svelte' },
    { id: 'tailwind', name: 'Tailwind CSS', category: 'Frontend', icon: 'tailwindcss' },
    { id: 'bootstrap', name: 'Bootstrap', category: 'Frontend', icon: 'bootstrap' },
    { id: 'sass', name: 'Sass', category: 'Frontend', icon: 'sass' },
    { id: 'redux', name: 'Redux', category: 'Frontend', icon: 'redux' },
    { id: 'html5', name: 'HTML5', category: 'Frontend', icon: 'html5' },
    { id: 'css3', name: 'CSS3', category: 'Frontend', icon: 'css3' },

    // Backend / API
    { id: 'nodejs', name: 'Node.js', category: 'Backend/API', icon: 'nodejs' },
    { id: 'express', name: 'Express', category: 'Backend/API', icon: 'express' },
    { id: 'django', name: 'Django', category: 'Backend/API', icon: 'django', customIconUrl: 'https://cdn.simpleicons.org/django/092E20', link: 'https://www.djangoproject.com/' },
    { id: 'flask', name: 'Flask', category: 'Backend/API', icon: 'flask', customIconUrl: 'https://cdn.simpleicons.org/flask/000000', link: 'https://flask.palletsprojects.com/' },
    { id: 'spring', name: 'Spring', category: 'Backend/API', icon: 'spring' },
    { id: 'laravel', name: 'Laravel', category: 'Backend/API', icon: 'laravel' },
    { id: 'dotnet', name: '.NET', category: 'Backend/API', icon: 'dot-net' },
    { id: 'hadoop', name: 'Hadoop', category: 'Backend/API', icon: 'hadoop' },
    { id: 'kafka', name: 'Kafka', category: 'Backend/API', icon: 'kafka', customIconUrl: 'https://www.vectorlogo.zone/logos/apache_kafka/apache_kafka-icon.svg', link: 'https://kafka.apache.org/' },
    { id: 'graphql', name: 'GraphQL', category: 'Backend/API', icon: 'graphql', customIconUrl: 'https://www.vectorlogo.zone/logos/graphql/graphql-icon.svg', link: 'https://graphql.org' },
    { id: 'nestjs', name: 'NestJS', category: 'Backend/API', icon: 'nestjs' },
    { id: 'rabbitmq', name: 'RabbitMQ', category: 'Backend/API', icon: 'rabbitmq' },
    { id: 'nginx', name: 'Nginx', category: 'Backend/API', icon: 'nginx' },
    { id: 'electron', name: 'Electron', category: 'Backend/API', icon: 'electron' },

    // Database / Cache
    { id: 'postgresql', name: 'PostgreSQL', category: 'Database/Cache', icon: 'postgresql', customIconUrl: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/postgresql/postgresql-original-wordmark.svg', link: 'https://www.postgresql.org' },
    { id: 'mysql', name: 'MySQL', category: 'Database/Cache', icon: 'mysql', customIconUrl: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/mysql/mysql-original-wordmark.svg', link: 'https://www.mysql.com/' },
    { id: 'mongodb', name: 'MongoDB', category: 'Database/Cache', icon: 'mongodb', customIconUrl: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/mongodb/mongodb-original-wordmark.svg', link: 'https://www.mongodb.com/' },
    { id: 'redis', name: 'Redis', category: 'Database/Cache', icon: 'redis', customIconUrl: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/redis/redis-original-wordmark.svg', link: 'https://redis.io' },
    { id: 'supabase', name: 'Supabase', category: 'Database/Cache', icon: 'supabase' },
    { id: 'firebase', name: 'Firebase', category: 'Database/Cache', icon: 'firebase' },
    { id: 'oracle', name: 'Oracle', category: 'Database/Cache', icon: 'oracle' },
    { id: 'couchdb', name: 'CouchDB', category: 'Database/Cache', icon: 'couchdb' },
    { id: 'cassandra', name: 'Cassandra', category: 'Database/Cache', icon: 'cassandra' },
    { id: 'cockroachdb', name: 'CockroachDB', category: 'Database/Cache', icon: 'cockroachdb', customIconUrl: 'https://cdn.worldvectorlogo.com/logos/cockroachdb.svg', link: 'https://www.cockroachlabs.com/product/cockroachdb/' },
    { id: 'hive', name: 'Hive', category: 'Database/Cache', icon: 'hive', customIconUrl: 'https://www.vectorlogo.zone/logos/apache_hive/apache_hive-icon.svg', link: 'https://hive.apache.org/' },
    { id: 'elasticsearch', name: 'Elasticsearch', category: 'Database/Cache', icon: 'elasticsearch' },
    { id: 'sqlite', name: 'SQLite', category: 'Database/Cache', icon: 'sqlite' },
    { id: 'mariadb', name: 'MariaDB', category: 'Database/Cache', icon: 'mariadb' },
    { id: 'mssql', name: 'MS SQL', category: 'Database/Cache', icon: 'sql-server', customIconUrl: 'https://www.svgrepo.com/show/303229/microsoft-sql-server-logo.svg', link: 'https://www.microsoft.com/en-us/sql-server' },

    // Cloud / DevOps
    { id: 'amazonaws', name: 'AWS', category: 'Cloud/DevOps', icon: 'amazonwebservices', customIconUrl: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/amazonwebservices/amazonwebservices-original-wordmark.svg', link: 'https://aws.amazon.com' },
    { id: 'azure', name: 'Azure', category: 'Cloud/DevOps', icon: 'azure', customIconUrl: 'https://www.vectorlogo.zone/logos/microsoft_azure/microsoft_azure-icon.svg', link: 'https://azure.microsoft.com/en-in/' },
    { id: 'gcp', name: 'Google Cloud', category: 'Cloud/DevOps', icon: 'googlecloud', customIconUrl: 'https://www.vectorlogo.zone/logos/google_cloud/google_cloud-icon.svg', link: 'https://cloud.google.com' },
    { id: 'docker', name: 'Docker', category: 'Cloud/DevOps', icon: 'docker' },
    { id: 'kubernetes', name: 'Kubernetes', category: 'Cloud/DevOps', icon: 'kubernetes' },
    { id: 'git', name: 'Git', category: 'Cloud/DevOps', icon: 'git' },
    { id: 'jenkins', name: 'Jenkins', category: 'Cloud/DevOps', icon: 'jenkins' },

    // Testing
    { id: 'cypress', name: 'Cypress', category: 'Testing', icon: 'cypress', customIconUrl: 'https://raw.githubusercontent.com/simple-icons/simple-icons/6e46ec1fc23b60c8fd0d2f2ff46db82e16dbd75f/icons/cypress.svg', link: 'https://www.cypress.io' },
    { id: 'playwright', name: 'Playwright', category: 'Testing', icon: 'playwright' },
    { id: 'selenium', name: 'Selenium', category: 'Testing', icon: 'selenium' },
    { id: 'jest', name: 'Jest', category: 'Testing', icon: 'jest', customIconUrl: 'https://www.vectorlogo.zone/logos/jestjsio/jestjsio-icon.svg', link: 'https://jestjs.io' },
    { id: 'mocha', name: 'Mocha', category: 'Testing', icon: 'mocha' },
    { id: 'jasmine', name: 'Jasmine', category: 'Testing', icon: 'jasmine' },

    // Software Tools
    { id: 'photoshop', name: 'Photoshop', category: 'Software Tools', icon: 'photoshop' },
    { id: 'illustrator', name: 'Illustrator', category: 'Software Tools', icon: 'illustrator' },
    { id: 'xd', name: 'Adobe XD', category: 'Software Tools', icon: 'xd' },
    { id: 'figma', name: 'Figma', category: 'Software Tools', icon: 'figma' },
    { id: 'framer', name: 'Framer', category: 'Software Tools', icon: 'framer', customIconUrl: 'https://www.vectorlogo.zone/logos/framer/framer-icon.svg', link: 'https://www.framer.com/' },
    { id: 'blender', name: 'Blender', category: 'Software Tools', icon: 'blender' },
    { id: 'matlab', name: 'MATLAB', category: 'Software Tools', icon: 'matlab' },
    { id: 'postman', name: 'Postman', category: 'Software Tools', icon: 'postman' },
    { id: 'insomnia', name: 'Insomnia', category: 'Software Tools', icon: 'insomnia' },
    //{ id: 'bruno', name: 'Bruno', category: 'Software Tools', icon: 'bruno' },
    { id: 'visualstudiocode', name: 'VS Code', category: 'Software Tools', icon: 'vscode' },

    // Game Engines
    { id: 'unity', name: 'Unity', category: 'Game Engines', icon: 'unity' },
    { id: 'unreal', name: 'Unreal Engine', category: 'Game Engines', icon: 'unrealengine' },

    // Other
    { id: 'linux', name: 'Linux', category: 'Other', icon: 'linux' },
    { id: 'heroku', name: 'Heroku', category: 'Other', icon: 'heroku', customIconUrl: 'https://www.vectorlogo.zone/logos/heroku/heroku-icon.svg', link: 'https://heroku.com' },
    { id: 'appwrite', name: 'Appwrite', category: 'Other', icon: 'appwrite', customIconUrl: 'https://www.vectorlogo.zone/logos/appwriteio/appwriteio-icon.svg', link: 'https://appwrite.io' },
    { id: 'chartjs', name: 'Chart.js', category: 'Other', icon: 'chartjs' },
    { id: 'grafana', name: 'Grafana', category: 'Other', icon: 'grafana' },
    { id: 'wordpress', name: 'WordPress', category: 'Other', icon: 'wordpress' },
    { id: 'arduino', name: 'Arduino', category: 'Other', icon: 'arduino' },
];
